### PR TITLE
Integration of logspout with dind

### LINKED ISSUE #80: Streaming logs of inner containers out to the outer one
I think that working with Docker in Docker would be much easier if `docker logs` would stream logs of inner containers with a different colors each. 

This could look like this (the gif comes from our [blog post](http://container-solutions.com/?p=3031]))
mydind

A PR follows.

### PR DESCRIPTION
**Pull request by lguminski**
closes #80

### CODE REVIEW

**Comment by jpetazzo** [comment]
Oh, this is really nice! But I'm not a huge fan of adding a mandatory extra dependency... I'd love to know what other people think? Should we merge it by default, or make a separate image maybe ... ?

**Comment by lguminski** [comment]
Well, the feature sped up our development, so I think others would also benefit. But I understand the concerns.

**Comment by jpetazzo** [comment]
There is now an official [docker:dind](https://hub.docker.com/_/docker/) image upstream!

I can suggest two options:
- find a way to integrate your logspout work with it somehow;
- maintain your own fork of "my" dind repo.

If you choose to do the latter, I'll be happy to reference your repo in the README of this one to indicate that it's more up-to-date!

**Comment by lguminski** [comment]
Thank you. That sounds reasonable. I will think how to proceed.

**Pull request closed without merging**
