### PR TITLE
Updated base image to extend Ubuntu 14.10

### PR DESCRIPTION
**Pull request by phillbarber**

### CODE REVIEW

**Comment by thaJeztah** [comment]
I'm not sure, 14.04 is a LTS release, whereas 14.10 isn't. Also, 14.10 will be replaced with 15.04 soon and EOL for 14.10 is July 2015 (see [Ubuntu releases](https://wiki.ubuntu.com/Releases)

Any particular reason you want to update to 14.10?

**Comment by phillbarber** [comment]
Hi Sebastiaan,
   Thanks so much for your response.

That's a good point so I can understand why you don't want to accept the
pull request.

My reason for updating to 14.10 was due to the fact that I was trying to
install open-jdk-8 in my dockerfile but it's not available in the apt
repositories under ubuntu 14.04.

Thanks

On Thu, Jan 29, 2015 at 7:23 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> I'm not sure, 14.04 is a LTS release, whereas 14.10 isn't. Also, 14.10
> will be replaced with 15.04 soon and EOL for 14.10 is July 2015 (see Ubuntu
> releases <https://wiki.ubuntu.com/Releases>
>
> Any particular reason you want to update to 14.10?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jpetazzo/dind/pull/48#issuecomment-72086992>.
>



-- 

Pergola Software Limited

Company number:  09275615 (incorporated in England and Wales)
Registered office:  5 Beaumont Gate, Shenley Hill,  Radlett,  WD7 7AR

**Comment by thaJeztah** [comment]
Well, I'm not the maintainer. Just wanted to mention the reasons for me *personally* to not being in favor of this change.

Perhaps running a containerized version of JDK would work? Or do you need it to be inside the dind container directly?

**Comment by phillbarber** [comment]
Yes, sadly I need it all in one container.

Thanks

Pergola Software Limited

Company number:  09275615 (incorporated in England and Wales)

Registered office:  5 Beaumont Gate, Shenley Hill,  Radlett,  WD7 7AR

**Comment by mgasner** [comment]
You may be able to build OpenJDK 8 from source on 14.04 -- https://github.com/hgomez/obuildfactory/wiki/How-to-build-and-package-OpenJDK-8-with-OpenJFX-on-Linux

**Comment by jpetazzo** [comment]
Hi!

Thanks for the contribution. *However*, I'm a huuuuge fan of LTS releases, and I'd rather stick to Ubuntu 14.04.

That being said, I would be more than happy to find a way to help you to achieve what you want!

If I understand correctly, you want to run `…something…` that:

- relies on OpenJDK8 (which doesn't install easily on 14.04)
- wants to start containers with Docker

Is that right?

**Comment by jpetazzo** [comment]
I'm not actively maintaining this repository anymore.

I will continue to consider small-impact PRs, but I would advise people to:
- check the [official `docker` images on the Docker Hub](https://hub.docker.com/_/docker/), as they have a `dind` variant specifically designed to run Docker-in-Docker;
- do their own thing with a fork of this repository if that's easier for their workflow.

Thank you!

**Pull request closed without merging**
