### PR TITLE
Add space expansion to $DOCKER_DAEMON_ARGS

### PR DESCRIPTION
**Pull request by alexandresalome**
When providing multiple arguments through ``$DOCKER_DAEMON_ARGS``, it is interpreted as a single argument to the docker daemon:

```
$ docker -d '--dns-search=dns.acme.org --dns 1.2.3.4'
Usage: docker [OPTIONS] COMMAND [arg...]

A self-sufficient runtime for linux containers.

# ...

Run 'docker COMMAND --help' for more information on a command.
```

This patch SHOULD solve the problem

### CODE REVIEW

**Comment by alexandresalome** [comment]
The problem only occurs on ZSH, not in Bash

**Comment by jpetazzo** [comment]
Nice! I'm not able to test that right now; were you able to double-check that the new version works correctly on bash and zsh?

Thanks a lot!

**Comment by alexandresalome** [comment]
This fix only makes sense if you source the script from zsh.

A very particular usage, so it makes no sense to merge it

**Comment by jpetazzo** [comment]
OK. Thanks anyway for looking on this; it might come up useful for people willing to use zsh with dind!

**Pull request closed without merging**
